Iceflow with icepyx notebook
nsidc/iceflow pull request #50
Opened 2024-10-30 17:19 UTC by trey-stafford

2024-11-01 19:27 UTC, asteiker requested changes
I will commit updates I made while I was reviewing. For iceflow-example, I cleared the code outputs because I ran into errors with my install. For iceflow-with-icepyx I tried not to actually run the cells but I accidentally did on atl06 resampling block. 

Overall these notebooks are excellent and most of my comments, other than the install issues, are just minor suggestions to improve the flow and written guidance.

2024-11-08 17:37 UTC, trey-stafford commented on docs/iceflow-example.ipynb
This is a good observation, I created an issue here to address: https://github.com/nsidc/iceflow/issues/51

2024-11-08 17:42 UTC, trey-stafford commented on notebooks/iceflow-example.ipynb
Yes, this is a bit confusing and could use some documentation. I setup the `notebooks/` directory for development, and have a script there that renders the notebooks for the docs (which get placed in the `docs/` dir). 

The `notebooks/` directory contains the source-of-truth, and is what we should make changes against. 

I know you made some changes to the rendered `docs/` notebooks, which is not a problem! I will transfer those changes to the `notebooks/` copies and re-render.

2024-11-08 17:42 UTC, trey-stafford commented on notebooks/iceflow-with-icepyx.ipynb
Yes, see my comment in https://github.com/nsidc/iceflow/pull/50#discussion_r1834828618

2024-11-08 18:04 UTC, trey-stafford commented on notebooks/iceflow-example.ipynb
fe91a15

2024-11-08 18:13 UTC, trey-stafford commented on notebooks/iceflow-example.ipynb
I also updated the `CONTRIBUTING.md` to include some additional information on developing jupyter notebooks.

2024-11-08 18:42 UTC, trey-stafford commented on docs/iceflow-with-icepyx.ipynb
I updated the notebooks to use `df.head()` wherever we preview dataframes. Looks much more compact! 35dcc10

2024-11-08 18:42 UTC, trey-stafford commented on docs/iceflow-example.ipynb
I updated the notebooks to use `df.head()` wherever we preview dataframes. Looks much more compact! 35dcc10

2024-11-08 18:53 UTC, trey-stafford commented on docs/iceflow-example.ipynb
I added a note to the beginning of the example notebook about the `iceflow-with-icepyx` notebook:

> To learn about how to download and manage larger amounts of data across many datasets with nsidc-iceflow, see the [Using iceflow with icepyx to Generate an Elevation Timeseries]() notebook.

dd75b99

I'm also going to add some higher-level docs about the library and supported datasets. That seems like a gap right now.

2024-12-09 17:51 UTC, trey-stafford commented on docs/iceflow-example.ipynb
Improvements added in #53

2024-12-09 18:15 UTC, merged